### PR TITLE
Add blaze-quality-reporting-ui

### PR DESCRIPTION
**Pull request by martinbreu**
Should it work with an empty database?
And is it possible to deliver some Measures as default?

### CODE REVIEW

**Comment by alexanderkiel** [comment]
It should work with empty database. Can you please try to create a Measure with this setup? The Measures will be delivered trough our IG.

**Comment by martinbreu** [comment]
image

**Comment by martinbreu** [comment]
An empty database works as well.

**Comment by martinbreu** [comment]
How will the Measures/Libraries be delivered through our IG?
Now is all empty without documentation or links to CQL examples

**Comment by alexanderkiel** [comment]
This issue is about adding the Measure Bundle to the IG: https://github.com/samply/bbmri-fhir-ig/issues/63

**Pull request merged**
